import { create } from "zustand";

const translations = {
  en: {
    dashboard: "Dashboard",
    signin: "Sign In",
    signup: "Sign Up",
    logout: "Logout",
    welcome_back: "Welcome Back",
    signin_to_manage: "Sign in to manage your tasks",
    dashboard_subtitle: "Track, manage and organize your tasks easily.",
    email: "Email Address",
    password: "Password",
    fullname: "Full Name",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    create_account: "Create Account",
    search: "Search tasks...",
    filter_all: "All Tasks",
    filter_pending: "Pending",
    filter_completed: "Completed",
    stats_total: "Total Tasks",
    stats_pending: "In Progress",
    stats_completed: "Completed",
    create_task: "Create New Task",
    no_tasks: "No tasks found",
    no_tasks_desc: "You don't have any tasks yet. Start by creating one!",
    low: "Low",
    medium: "Medium",
    high: "High",
    pending: "Pending",
    completed: "Completed",
    title: "Title",
    description: "Description",
    priority: "Priority",
    cancel: "Cancel",
    save: "Save Changes",
    delete_confirm: "Are you sure you want to delete this task?",
    back: "Back to Dashboard",
    created: "Created",
    status: "Status",
    mark_done: "Mark as Done",
    hi: "Hi",
    start_date: "Start Date",
    end_date: "End Date",
    duration: "Duration",
    overdue: "Overdue",
    in_progress: "In Progress",
    completed_status: "Completed",
    save_edit: "Save",
    close: "Close",
    set_start: "Set Start",
    set_end: "Set End",
    stats_total_desc: "Updated just now",
    stats_pending_desc: "Still in progress",
    stats_completed_desc: "Tasks done!",
    no_description: "No description provided.",
    title_placeholder: "E.g. Design User Interface",
    details: "Details",
    stats_overdue_desc: "Tasks that need urgent attention!",
  },
  th: {
    dashboard: "แดชบอร์ด",
    signin: "เข้าสู่ระบบ",
    signup: "ลงทะเบียน",
    logout: "ออกจากระบบ",
    welcome_back: "ยินดีต้อนรับกลับมา",
    signin_to_manage: "ลงชื่อเข้าใช้เพื่อจัดการงานของคุณ",
    dashboard_subtitle: "ติดตาม จัดการ และจัดระเบียบงานของคุณได้อย่างง่ายดาย",
    email: "ที่อยู่อีเมล",
    password: "รหัสผ่าน",
    fullname: "ชื่อ-นามสกุล",
    dont_have_account: "ยังไม่มีบัญชี?",
    already_have_account: "มีบัญชีอยู่แล้ว?",
    create_account: "สร้างบัญชี",
    search: "ค้นหางาน...",
    filter_all: "งานทั้งหมด",
    filter_pending: "รอดำเนินการ",
    filter_completed: "เสร็จสิ้นแล้ว",
    stats_total: "งานทั้งหมด",
    stats_pending: "กำลังดำเนินการ",
    stats_completed: "เสร็จสิ้นแล้ว",
    create_task: "สร้างงานใหม่",
    no_tasks: "ไม่พบงาน",
    no_tasks_desc: "คุณยังไม่มีงานใดๆ เริ่มต้นด้วยการสร้างงานใหม่ได้เลย!",
    low: "ต่ำ",
    medium: "กลาง",
    high: "สูง",
    pending: "รอดำเนินการ",
    completed: "เสร็จสิ้น",
    title: "ชื่อเรื่อง",
    description: "รายละเอียด",
    priority: "ความสำคัญ",
    cancel: "ยกเลิก",
    save: "บันทึกการเปลี่ยนแปลง",
    delete_confirm: "คุณแน่ใจหรือไม่ว่าต้องการลบงานนี้?",
    back: "กลับไปที่แดชบอร์ด",
    created: "สร้างเมื่อ",
    status: "สถานะ",
    mark_done: "ทำเครื่องหมายว่าเสร็จ",
    hi: "สวัสดี",
    start_date: "วันที่เริ่ม",
    end_date: "วันที่สิ้นสุด",
    duration: "ระยะเวลา",
    overdue: "เลยกำหนด",
    in_progress: "กำลังดำเนินการ",
    completed_status: "สำเร็จ",
    save_edit: "บันทึก",
    close: "ปิด",
    set_start: "เริ่มวันที่",
    set_end: "สิ้นสุดวันที่",
    stats_total_desc: "อัปเดตเมื่อครู่",
    stats_pending_desc: "ยังคงรอดำเนินการ",
    stats_completed_desc: "เสร็จงานแล้ว!",
    no_description: "ไม่มีคำอธิบาย",
    title_placeholder: "เช่น ออกแบบหน้าจอผู้ใช้",
    details: "รายละเอียด",
    stats_overdue_desc: "งานที่ต้องรีบทำ!",
  },
};

const useLanguageStore = create((set) => ({
  lang: localStorage.getItem("lang") || "en",
  setLang: (lang) => {
    localStorage.setItem("lang", lang);
    set({ lang });
  },
  t: (key) => {
    const currentLang = localStorage.getItem("lang") || "en";
    return translations[currentLang][key] || key;
  },
}));

export default useLanguageStore;
export { translations };
